#!/bin/bash
# Output colors
NORMAL="\\033[0;39m"
RED="\\033[1;31m"
BLUE="\\033[1;34m"

start_services() {
  docker-compose up ${*:1} -d
}

stop_services() {
  docker-compose down ${*:1}
}

start() {
  docker-compose up $1 ${*:2}
}

logs() {
  docker-compose logs --follow
}

"$@"
